- name: ping the server
  hosts: web
  tasks: 
  - name: pingthe server
    ansible.builtin.ping:

- name: ping the server
  hosts: web
  tasks: 
  - name: pingthe server
    ansible.builtin.ping:    

