- name: printing the variables
  hosts: web
  vars_prompt:
  - name: course
    prompt: enter the course name
  tasks: 
  - name: printing the variables
    ansible.builtin.debug:
      msg: "hi {{course}}"
