     - name: adding user
       hosts: web
       become: yes
       tasks: 
       - name: check naveen user there or not
         ansible.builtin.command: id raju
         register: user
         ignore_errors: true


       - name: printing values
         ansible.builtin.debug: 
           msg: "{{user}}"

       - name: check raju user there or not
         ansible.builtin.command: useradd raju
         when: user.rc!=0


        






      

   

  