     - name: adding user
       hosts: web
       become: yes
       tasks: 
       - name: check naveen user there or not
         ansible.builtin.command: id raju
         register: user


       - name: printing values
         ansible.builtin.debug: 
           msg: "{{user}}"



      

   

  