- name: conditions
  hosts: web
  vars:
    my_num: 120
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true

   

  - name: printing
    ansible.builtin.debug: "{{user}}" 
      