- name: conditions
  hosts: web
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: Print 
    ansible.builtin.debug:  
      msg: {{USER}}
      

   

  