     - name: adding user
       hosts: web
       tasks: 
       - name: check naveen user there or not
         ansible.builtin.command: useradd naveen
         register: user


       - name: printing values
         ansible.builtin.debug: 
         


      

   

  