- name: facts
  hosts: web
  become: yes
  tasks:
  - name: facts 
    ansible.builtin.debug:
      msg: "{{ansible_facts}}"

  - name: install nginx if it is redhat
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family=="RedHat"   


        
    
