- name: Install MySQL and Start
  hosts: localhost
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present
      notify: Start MySQL  # Notify to start MySQL if installed

  handlers:
    - name: Start MySQL
      ansible.builtin.service:
        name: mysql
        state: started  # This runs if MySQL was just installed
