- name: installing nginx
  hosts: local
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present


  - name: installing nginx
    ansible.builtin.package:
      name: mysql-server
      state: present 
    notify: nginx restart     

  - name: printing msg
    ansible.builtin.debug:
    notify: nginx restart


   