- name: Install and Start Nginx
  hosts: localhost
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: Restart nginx  # Notify the handler only if installed

  