
- name: Install nginx and mysql-server
  hosts: local
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: docker
        state: present
      notify: Restart nginx  

    - name: Install mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: present
      notify: Restart nginx

    - name: Print message
      ansible.builtin.debug:
        msg: "MySQL server has been installed."
      notify: Restart nginx

 
