- name: Install nginx
  hosts: localhost
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: nginx service
    - name: nginx service
      ansible.builtin.service:
       name: nginx
       state : restarted