- name: Install and Start Nginx
  hosts: localhost
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: Restart nginx  # Notify the handler only if installed

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted  # This runs only if notified
