- name: installing nginx
  hosts: web
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == "RedHat" 


  - name: installing nginx
    ansible.builtin.apt:
     name: docker
     state: present
    when: ansible_os_family=="UBUNTU" 
  
