- name: installing nginx
  hosts: web
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family=="REDHAT" 


  - name: installing nginx
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family=="REDHAT" 
  
